### ISSUE TITLE
Error installing xen tools 

### ISSUE THREAD

**Issue by heat87** [01org/XenGT-Preview-xen#18]
I try to install XenGT on Xubuntu 14.04.2 but get the following error when i try to execute 
"make install-tools PYTHON_PREFIX_ARG="
--------------------------------------------
Traceback (most recent call last):
  File "./tools/layoutrom.py", line 630, in <module>
    main()
  File "./tools/layoutrom.py", line 607, in main
    info16 = parseObjDump(infile16, '16')
  File "./tools/layoutrom.py", line 538, in parseObjDump
    relocsection = sectionmap[sectionname]
KeyError: '.text.asm.out/../src/smp.c.77'
make[6]: *** [out/romlayout16.lds] Fehler 1
make[6]: Verzeichnis »/home/heat/Xengt/XenGT-Preview-kernel/XenGT-Preview-xen/xen-vgt/tools/firmware/seabios-dir-remote« wird verlassen
make[5]: *** [subdir-all-seabios-dir] Fehler 2
make[5]: Verzeichnis »/home/heat/Xengt/XenGT-Preview-kernel/XenGT-Preview-xen/xen-vgt/tools/firmware« wird verlassen
make[4]: *** [subdirs-all] Fehler 2
make[4]: Verzeichnis »/home/heat/Xengt/XenGT-Preview-kernel/XenGT-Preview-xen/xen-vgt/tools/firmware« wird verlassen
make[3]: *** [all] Fehler 2
make[3]: Verzeichnis »/home/heat/Xengt/XenGT-Preview-kernel/XenGT-Preview-xen/xen-vgt/tools/firmware« wird verlassen
make[2]: *** [subdir-install-firmware] Fehler 2
make[2]: Verzeichnis »/home/heat/Xengt/XenGT-Preview-kernel/XenGT-Preview-xen/xen-vgt/tools« wird verlassen
make[1]: *** [subdirs-install] Fehler 2
make[1]: Verzeichnis »/home/heat/Xengt/XenGT-Preview-kernel/XenGT-Preview-xen/xen-vgt/tools« wird verlassen
make: *** [install-tools] Fehler 2
---------------------------------------------------
can anyone help me solving this error?

**Comment by albionxyz** [comment]
It looks like you have the python2/3 issue.
try PYTHON=python2
(See line 
make DESTDIR="$pkgdir" LANG=C PYTHON=python2 install-{xen,tools,stubdom} 
at 
https://aur.archlinux.org/packages/xe/xen-4.3/PKGBUILD)

**Comment by heat87** [comment]
thank you for the quicke reply.
I tried to execute "make DESTDIR="$pkgdir" LANG=C PYTHON=python2 install-{xen,tools,stubdom} " And i tried to execute "make install-tools PYTHON_PREFIX_ARG=python2". And now i get the following error:


libxlu_cfg_y.c: In function ‘xlu__cfg_yyparse’:
libxlu_cfg_y.c:1311:41: error: ‘scanner’ undeclared (first use in this function)
       yychar = yylex (&yylval, &yylloc, scanner);
                                         ^
libxlu_cfg_y.c:1311:41: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [libxlu_cfg_y.o] Fehler 1
make[3]: Verzeichnis »/home/heat/Xengt/XenGT-Preview-kernel/XenGT-Preview-xen/xen-vgt/tools/libxl« wird verlassen
make[2]: *** [subdir-install-libxl] Fehler 2
make[2]: Verzeichnis »/home/heat/Xengt/XenGT-Preview-kernel/XenGT-Preview-xen/xen-vgt/tools« wird verlassen
make[1]: *** [subdirs-install] Fehler 2
make[1]: Verzeichnis »/home/heat/Xengt/XenGT-Preview-kernel/XenGT-Preview-xen/xen-vgt/tools« wird verlassen
make: *** [install-tools] Fehler 2



I am new to all these things an never worked with xen before so maybe i am doing something very simple wrong.

**Comment by pankajk87** [comment]
I am getting the same error

**Comment by jikesong** [comment]
https://github.com/01org/igvtg-xen
https://github.com/01org/igvtg-kernel
https://github.com/01org/igvtg-qemu

Hi we have moved to new home as above, with XenGT and KVMGT merged.
Would you have a try with the new repos?


--
Thanks,
Jike
